#!/usr/bin/env bash

set -e
set -u
set -o pipefail

printf "!! cargo fetch\n\n"
cargo fetch --locked

common_args=(
	--frozen
	# exclude "devel"
	--no-default-features
)

export RUST_BACKTRACE=1

printf "!! configure nginx\n\n"
cargo xtask configure

printf "!! generate openssl.cnf for ossl_hsm\n\n"
export OPENSSL_CONF="$PWD/ossl_hsm/openssl.cnf"
cat >"$OPENSSL_CONF" <<-EOF
	openssl_conf = openssl_init

	[openssl_init]
	providers = provider_sect

	[provider_sect]
	ossl_hsm = ossl_hsm_sect
	default = default_sect

	[ossl_hsm_sect]
	module = $PWD/target/debug/libossl_hsm.so
	activate = 1

	[default_sect]
	activate = 1
EOF

printf "!! tests\n\n"
tests() {
	set +e
	(
		shopt -s nullglob
		# shellcheck disable=SC1091
		. /usr/local/share/cov-env

		cargo nextest run --workspace ${NEXTEST_FILTERSET:+--filterset "$NEXTEST_FILTERSET"}
		local result=$?

		if [[ -f prefix/test.log ]]; then
			cat prefix/test.log || :
		fi

		# n.b.: --no-run is deprecated, but report doesn't support --workspace…
		cargo llvm-cov --no-run --workspace
		cargo llvm-cov --no-run --workspace --lcov --output-path coverage.lcov || :
		cargo llvm-cov clean --workspace || :
		exit $result
	)
	result=$?
	set -e
	return $result
}

set -e
tests
test_result=$?
set +e

printf "!! build nginx module\n\n"
cargo build "${common_args[@]}" --release --lib

printf "!! build hsm_sim\n\n"
cargo build "${common_args[@]}" --release -p hsm_sim

printf "!! build ossl_hsm\n\n"
cargo build "${common_args[@]}" --release -p ossl_hsm

printf "!! clippy\n\n"
cargo clippy "${common_args[@]}" --release --workspace

printf "!! clippy json\n\n"
cargo clippy "${common_args[@]}" --release --workspace --message-format json >clippy.json

printf "!! write .pkg-version\n\n"
cargo metadata --format-version 1 | jq -r '.packages | map(select(.name == "ngx_pep")) | .[0].version' \
	>.pkg-version || :

printf "!! write ngx_pep.cdx.json\n\n"
cargo cyclonedx -f json -a

printf "!! mdbook\n\n"
mdbook build book

exit $test_result
