sonar.sourceEncoding=UTF-8
sonar.projectKey=zeta_zeta-guard_ngx_pep_9268e16a-4e01-4f43-8b66-f5499c59efba
sonar.rust.clippy.enabled=false
sonar.rust.clippyReport.reportPaths=clippy.json
sonar.sources=src,libasl/src,hsm_sim/src,ossl_hsm/src
# hsm_sim/src/main.rs: not testable with integration tests
# libasl/src/client.rs: only used for tests/purl
sonar.exclusions=prefix/**,target/**,src/tests.rs,src/stubs.rs,src/client/**,src/its/**,libasl/src/client.rs,hsm_sim/src/main.rs,hsm_sim/src/tests.rs
sonar.tests=tests,src/client,src/tests.rs,src/stubs.rs,src/its,libasl/tests,libasl/src/client.rs,purl/src,hsm_sim/src/tests.rs,hsm_sim/tests
sonar.rust.lcov.reportPaths=coverage.lcov
