env RUST_LOG;
env RUST_TRACE;

# https://docs.rs/opentelemetry_sdk/0.32.1/opentelemetry_sdk/
env OTEL_SERVICE_NAME;
env OTEL_RESOURCE_ATTRIBUTES;

env OTEL_TRACES_SAMPLER;
env OTEL_TRACES_SAMPLER_ARG;

env OTEL_SPAN_ATTRIBUTE_COUNT_LIMIT;
env OTEL_SPAN_EVENT_COUNT_LIMIT;
env OTEL_SPAN_LINK_COUNT_LIMIT;

env OTEL_BSP_SCHEDULE_DELAY;
env OTEL_BSP_MAX_QUEUE_SIZE;
env OTEL_BSP_MAX_EXPORT_BATCH_SIZE;
env OTEL_BSP_MAX_CONCURRENT_EXPORTS;

env OTEL_BLRP_SCHEDULE_DELAY;
env OTEL_BLRP_MAX_QUEUE_SIZE;
env OTEL_BLRP_MAX_EXPORT_BATCH_SIZE;

env OTEL_METRIC_EXPORT_INTERVAL;

# NOTE: the only supported OTEL_EXPORTER_* env. The protocol is always gRPC.
env OTEL_EXPORTER_OTLP_ENDPOINT;
