user nginx;
worker_processes auto;

load_module modules/libngx_pep.so;

error_log /dev/stdout;
pid /tmp/nginx.pid;

events {
    worker_connections 16384;
    multi_accept on;
    use epoll;
}

http {
    include common.conf;

    access_log /dev/stdout main;

    client_body_temp_path /tmp/client_body_temp;
    proxy_temp_path /tmp/proxy_temp;
    scgi_temp_path /tmp/scgi_temp;
    uwsgi_temp_path /tmp/uwsgi_temp;

    ### Global Config

    pep_pdp_issuer https://zeta-staging.spree.de/auth/realms/zeta-guard;
    ## server hosting PoPP entity statement at /.well-known/openid-federation
    ## optional if no locations use pep_require_popp
    # pep_popp_issuer https://example.org;
    # pep_http_client_idle_timeout 30; # s
    # pep_http_client_max_idle_per_host 64;
    # pep_http_client_tcp_keepalive 30; # s
    # pep_http_client_connect_timeout 2; # s
    # pep_http_client_timeout 10; # s
    # pep_http_client_accept_invalid_certs off;
    ## enable or disable no-travel enforcement (ip address consistency)
    # pep_no_travel off;
    ## NOTE: acquire aslkeys and enable these settings if you need ASL support
    ## NOTE: you must also include asl.conf in server below!
    # pep_asl_testing on;
    # pep_asl_signer_cert /etc/nginx/signer_cert.pem;
    # pep_asl_signer_key /etc/nginx/signer_key.pem;
    # pep_asl_ca_cert /etc/nginx/issuer_cert.pem;
    # pep_asl_roots_json /etc/nginx/roots.json;
    # pep_asl_root_ca FAKE.RCA1;
    ## cert: use AuthorityInformationAccess (AIA) from cert (default)
    ## off: disable OCSP checks
    ## https://ocsp.example.org: override responder, ignore cert AIA
    # pep_asl_ocsp_url cert;
    # pep_asl_ocsp_ttl 24h;

    ### Location Config
    ## These can be set per-location, but it is recommended to set them once globally, and
    ## only override in specific locations as needed.

    ## enable access phase handler to check access tokens, DPoP and, optionally, PoPP
    pep on;
    ## space separated list of required audiences
    pep_require_aud "https://zeta-staging.spree.de";
    ## space separated list of required scopes
    # pep_require_scope "openid profile email";
    ## clock leeway when checking exp,nbf,iat claims in s, default: 60
    # pep_leeway 60;
    ## implied dpop validity in s: iat + pep_dpop_validity + pep_leeway
    ## pep_dpop_validity 300;
    ## validate PoPP header and pass decoded claims as ZETA-PoPP-Token-Content to upstream
    # pep_require_popp off;
    ## implied ppop validity in s
    # pep_ppop_validity 31536000;

    server {
        listen 8080;
        # listen 8443 ssl;
        # ssl_certificate "tls.p256.pem";
        ## NOTE: set HSM_PROXY_ADDR="https://hsm:50051" environment variable to use
        ## store:hsm with the ossl_hsm provider
        # ssl_certificate_key "store:hsm:tls.p256";

        server_name localhost;

        root /usr/share/nginx/html;

        include server_common.conf;
        # include asl.conf;

        ## NOTE: configure your Fachdienst-URLS here
        # location / {
        #   proxy_http_version 1.1;
        #   proxy_pass "http://example.com/";
        # }
        #
        # location /ws {
        #   proxy_http_version 1.1;
        #   proxy_pass "http://example.com/ws";
        #   # see: common.conf
        #   proxy_set_header Upgrade $http_upgrade;
        #   proxy_set_header Connection $connection_upgrade;
        #   proxy_set_header Sec-WebSocket-Protocol $http_sec_websocket_protocol;
        #   location /ws/ {
        #     proxy_pass "http://example.com/ws/";
        #   }
        # }
    }
}
