[alias]
xtask = "run --manifest-path xtask/Cargo.toml --"

[env]
NGINX_SOURCE_DIR = { value = ".nginx", relative = true }
NGINX_VERSION = "1.29.5" # NOTE: keep in sync with .gitlab-ci.yml and Dockerfile
